### PR TITLE
Allow user to specify file format

### PR DESCRIPTION
**Pull request by kevindoveton**

### CODE REVIEW

**Review by lewisdaly — APPROVED** [review]
Do you need me to deploy this? Or can I give you access to the project in firebase so you can?

**Comment by kevindoveton** [comment]
I'm happy to deploy if you give me access - I'll need your env values as well.

**Comment by lewisdaly** [comment]
Sure

**Comment by lewisdaly** [comment]
@kevindoveton added you as an editor. The env file is just the API key in `gopass vessels/uncdf/dfstalk`, I don't think it's even used actually

**Pull request merged**
